#!/bin/bash

# Wrapper around standard unsquashfs tool to suppress non-fatal errors
#
# Copyright (c) 2023 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
#

# This wrapper script will show up as the first "unsquashfs" in the PATH - find
# the next one (if one exists).  Within the container used for some GISO builds
# there is no "which" tool so we roll our own.
UNSQUASHFS=$( IFS=:; for DIR in $PATH; do [ -x  $DIR/unsquashfs ] && echo $DIR/unsquashfs; done | sed -n '2 p' )

if [ -z "$UNSQUASHFS" ]; then
    echo "No version of unsquashfs available in $PATH"
    exit 1
fi

# Run the regular unsquashfs tool with the caller's arguments and suppress any
# non-fatal errors (i.e. if the tool return code is 2 then return 0).
$UNSQUASHFS "$@"

RC=$?
if [[ "$RC" == 2 ]]; then
    exit 0
else
    exit $RC
fi
